"""New field last_login for User

Revision ID: 81ea1e04418f
Revises: d9bc272a8068
Create Date: 2026-04-24 21:23:33.720737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ea1e04418f'
down_revision: Union[str, Sequence[str], None] = 'd9bc272a8068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cash_accounts', ['id'])
    op.create_unique_constraint(None, 'transaction_histories', ['id'])
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'last_login')
    op.drop_constraint(None, 'transaction_histories', type_='unique')
    op.drop_constraint(None, 'cash_accounts', type_='unique')
    # ### end Alembic commands ###
