"""Deleted field balance for CashAccount model

Revision ID: a0b4afd1ab6e
Revises: 7e23fe6b08f6
Create Date: 2026-04-25 21:40:31.141842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.security.password import PasswordService


# revision identifiers, used by Alembic.
revision: str = 'a0b4afd1ab6e'
down_revision: Union[str, Sequence[str], None] = '7e23fe6b08f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PASSWORD_HASH = PasswordService().hash_password('string')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_accounts', 'balance')

    users_table = sa.table(
        'users',
        sa.column('id', sa.Integer),
        sa.column('surname', sa.String),
        sa.column('name', sa.String),
        sa.column('patronymic', sa.String),
        sa.column('email', sa.String),
        sa.column('password_hash', sa.String),
        sa.column('role', sa.Enum(name='roleenum'))
    )

    cash_accounts_table = sa.table(
        'cash_accounts',
        sa.column('user_id', sa.Integer)
    )

    users_data = [
        {
            'surname': 'Test',
            'name': 'User',
            'patronymic': None,
            'email': 'test_user@example.com',
            'password_hash': PASSWORD_HASH,
            'role': 'USER',
        },
        {
            'surname': 'Test',
            'name': 'Admin',
            'patronymic': None,
            'email': 'test_admin@example.com',
            'password_hash': PASSWORD_HASH,
            'role': 'ADMIN',
        }
    ]

    op.bulk_insert(users_table, users_data)
    stmt = sa.select(users_table.c.id).where(users_table.c.email == 'test_user@example.com')
    test_user_id = op.get_bind().execute(stmt).scalar()

    op.bulk_insert(cash_accounts_table, [
        {'user_id': test_user_id}
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM cash_accounts WHERE user_id IN "
        "(SELECT id FROM users WHERE email = 'test_user@example.com')"
    )
    op.execute(
        "DELETE FROM users WHERE email IN "
        "('test_user@example.com', 'test_admin@example.com')"
    )

    op.add_column('cash_accounts', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###